LPS-138813
rodrigocunhaa/liferay-portal pull request #1021
Opened 2021-09-16 19:12 UTC by evanilson-santana

2021-09-16 19:12 UTC, liferay-continuous-integration commented
Please only forward necessary changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing DXP 7.4 GA1 and Portal 7.4 GA4 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-09-16 19:12 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-09-16 19:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/8/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com//userContent/jobs/test-portal-source-format/builds/8/jenkins-report.html">here</a>.</b></p>

2021-09-16 19:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e1ff16e8938589891df0d6e796214f74446abfb">2e1ff16e8938589891df0d6e796214f74446abfb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LPS-138813">LPS-138813</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/2325f1a907bf3d55ec5028c04ce4fce214c2dc27">2325f1a907bf3d55ec5028c04ce4fce214c2dc27</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/8/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/8/jenkins-report.html">here</a>.</h5></details></html>

2021-09-16 19:20 UTC, evanilson-santana commented
ci:test:sf

2021-09-16 19:40 UTC, rodrigocunhaa requested changes
Hi @evanilson-santana ,

Please see my comments and make the necessary changes.

Thanks!

2021-09-16 19:40 UTC, rodrigocunhaa commented on modules/apps/object/object-test/src/testFunctional/tests/tests/CreateObject.testcase
> +		CreateObject.viewObject(labelName = "CustomObject");
Hi @evanilson-santana ,

for this test, you need to view the Object details through the eye (view) option on the kebab menu,

You have to use the `ObjectAdmin.selectCustomObjectFieldKebabMenuOption` macro. If I'm not mistaken, this macro is broken, so you'll have to fix it too.

Thanks!

2021-09-16 19:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/6072/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-portal-source-format/builds/6072/jenkins-report.html">here</a>.</b></p>

2021-09-16 19:56 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2e1ff16e8938589891df0d6e796214f74446abfb">2e1ff16e8938589891df0d6e796214f74446abfb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LPS-138813">LPS-138813</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/2c1a5b7e7357b1e152474a3f06412617bbac873d">2c1a5b7e7357b1e152474a3f06412617bbac873d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6072/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6072/jenkins-report.html">here</a>.</h5></details></html>

2021-09-16 19:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/6072/">test-portal-source-format#6072</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/6072/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1021">rodrigocunhaa#1021</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1561912295">[master] ci:test:sf - evanilson-santana &gt; rodrigocunhaa - PR#1021 - 2021-09-16[12:50:43]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/1774/">publish-testray-report#1774</a><br/></div></div>

2021-09-17 17:14 UTC, evanilson-santana commented
Fixed.

2021-09-17 19:09 UTC, rodrigocunhaa commented
ci:forward

2021-09-17 19:09 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-09-17 19:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/30/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com//userContent/jobs/test-portal-source-format/builds/30/jenkins-report.html">here</a>.</b></p>

2021-09-17 19:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c1a5877759801048ce6dfdc8041fcd2c2607daf6">c1a5877759801048ce6dfdc8041fcd2c2607daf6</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LPS-138813">LPS-138813</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/c69883bbcb21f3c378b89fbae7849fee9263f091">c69883bbcb21f3c378b89fbae7849fee9263f091</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/30/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/30/jenkins-report.html">here</a>.</h5></details></html>

2021-09-17 19:13 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-33.liferay.com/job/test-portal-source-format/30//consoleFull)

2021-09-17 19:13 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/107437
[Console](https://test-1-33.liferay.com/job/test-portal-source-format/30//consoleFull)

2021-09-17 19:13 UTC, closed without merging

2021-09-17 19:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/30/">test-portal-source-format#30</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/30/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1021">rodrigocunhaa#1021</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1562216569">[master] ci:test:sf - evanilson-santana &gt; rodrigocunhaa - PR#1021 - 2021-09-17[12:09:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/100/">publish-testray-report#100</a><br/></div></div>

2021-09-17 19:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/412/">test-portal-acceptance-pullrequest(master)#412</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/412/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1021">rodrigocunhaa#1021</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1562216578">[master] ci:test:relevant - evanilson-santana &gt; rodrigocunhaa - PR#1021 - 2021-09-17[12:09:52]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/1324/">publish-testray-report#1324</a><br/></div></div>