LPS-138961
rodrigocunhaa/liferay-portal pull request #1036
Opened 2021-09-21 17:36 UTC by PauloVAS

2021-09-21 17:36 UTC, liferay-continuous-integration commented
Please only forward necessary changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing DXP 7.4 GA1 and Portal 7.4 GA4 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-09-21 17:36 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-09-21 17:36 UTC, PauloVAS commented
ci:test:sf

2021-09-21 17:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/392/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com//userContent/jobs/test-portal-source-format/builds/392/jenkins-report.html">here</a>.</b></p>

2021-09-21 17:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/60c178b91f14b75e9bd4b56cf43cf152c1dbb824">60c178b91f14b75e9bd4b56cf43cf152c1dbb824</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/LPS-138961">LPS-138961</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/00b0a5ad173e9b0d6ff1faad9a7db88b40d5f18e">00b0a5ad173e9b0d6ff1faad9a7db88b40d5f18e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/392/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/392/jenkins-report.html">here</a>.</h5></details></html>

2021-09-21 17:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/392/">test-portal-source-format#392</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/392/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1036">rodrigocunhaa#1036</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1562880400">[master] ci:test:sf - PauloVAS &gt; rodrigocunhaa - PR#1036 - 2021-09-21[10:37:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/1300/">publish-testray-report#1300</a><br/></div></div>

2021-09-21 22:28 UTC, rodrigocunhaa requested changes
Hi @PauloVAS ,

Please, check the changes that I requested.

Thanks!

2021-09-21 22:28 UTC, rodrigocunhaa commented on modules/apps/object/object-test/src/testFunctional/tests/macros/ObjectPortlet.macro
> +	}
You can remove this.

2021-09-21 22:28 UTC, rodrigocunhaa commented on modules/apps/object/object-test/src/testFunctional/tests/paths/ObjectPortlet.path
> +	</tr>
you can remove this

2021-09-21 22:28 UTC, rodrigocunhaa commented on modules/apps/object/object-test/src/testFunctional/tests/tests/ObjectPortlet.testcase
> +				fieldName = "text",
Change this to:
`fieldName = "customObjectField",`

2021-09-21 22:28 UTC, rodrigocunhaa commented on modules/apps/object/object-test/src/testFunctional/tests/tests/ObjectPortlet.testcase
> +				value = "Test text");
Change this to:
value = "Test text ${number}"

2021-09-21 22:28 UTC, rodrigocunhaa commented on modules/apps/object/object-test/src/testFunctional/tests/tests/ObjectPortlet.testcase
> +		ObjectPortlet.assertEntryRowNotDisplayed(rowNumber = "5");
Use `ObjectPortlet.viewEntry` and `ObjectPortlet.assertEntryNotPresent` here.

Check this as reference: https://github.com/rodrigocunhaa/liferay-portal/pull/1038/files

2021-09-22 18:19 UTC, PauloVAS commented
@rodrigocunhaa, fixed!

2021-09-22 18:20 UTC, PauloVAS commented
ci:test:sf

2021-09-22 18:20 UTC, PauloVAS commented
ci:test:sf

2021-09-22 18:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/256/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/256/jenkins-report.html">here</a>.</b></p>

2021-09-22 18:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e602cec549e6a92becc91731a57a2c041134cf98">e602cec549e6a92becc91731a57a2c041134cf98</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/LPS-138961">LPS-138961</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/f74a18a11efc117acdef165e9ce625dbc8022d75">f74a18a11efc117acdef165e9ce625dbc8022d75</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/256/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/256/jenkins-report.html">here</a>.</h5></details></html>

2021-09-22 18:25 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/256/">test-portal-source-format#256</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/256/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1036">rodrigocunhaa#1036</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1563181344">[master] ci:test:sf - PauloVAS &gt; rodrigocunhaa - PR#1036 - 2021-09-22[11:20:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/831/">publish-testray-report#831</a><br/></div></div>

2021-09-23 13:57 UTC, rodrigocunhaa commented
ci:forward

2021-09-23 13:57 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-09-23 13:57 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-09-23 13:58 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-32.liferay.com/job/forward-pullrequest/68//consoleFull)

2021-09-23 13:58 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/107669
[Console](https://test-1-32.liferay.com/job/forward-pullrequest/68//consoleFull)

2021-09-23 13:58 UTC, closed without merging

2021-09-23 17:13 UTC, rodrigocunhaa commented
Just started reviewing :)