LPS-141652
rodrigocunhaa/liferay-portal pull request #1330
Opened 2021-12-15 19:13 UTC by PauloVAS

2021-12-15 19:13 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-12-15 19:14 UTC, PauloVAS commented
ci:test:sf

2021-12-15 19:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/1444/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/1444/jenkins-report.html">here</a>.</b></p>

2021-12-15 19:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dc3a783d8eb395745aa94f025de65a93261a3a53">dc3a783d8eb395745aa94f025de65a93261a3a53</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/LPS-141652">LPS-141652</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/8712e7995b6b70179f65f8427dffe19bf7261afa">8712e7995b6b70179f65f8427dffe19bf7261afa</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/1444/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/1444/jenkins-report.html">here</a>.</h5></details></html>

2021-12-15 19:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/1444/">test-portal-source-format#1444</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/1444/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1330">rodrigocunhaa#1330</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1590963831">[master] ci:test:sf - PauloVAS &gt; rodrigocunhaa - PR#1330 - 2021-12-15[11:14:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/4928/">publish-testray-report#4928</a><br/></div></div>

2021-12-15 21:32 UTC, evanilson-santana commented on modules/apps/object/object-test/src/testFunctional/tests/CreateObject.testcase
> +		ObjectAdmin.addTabFieldsOnLayout(tabName = "Field Tab");
You don't need use this macro for this test

2021-12-15 21:48 UTC, evanilson-santana requested changes
Hi @PauloVAS,

Please, check my comments and make the necessary changes.

Let me know if you have any questions.

Thanks.

2021-12-15 21:48 UTC, evanilson-santana commented on modules/apps/object/object-test/src/testFunctional/tests/CreateObject.testcase
> +		ObjectAdmin.addTabFieldsOnLayout(tabName = "Field Tab");
You don't need to add one more Field Tab on this test

2021-12-15 21:48 UTC, evanilson-santana commented on modules/apps/object/object-test/src/testFunctional/macros/ObjectPortlet.macro
> +		Click(locator1 = "//a[contains(text(), 'Relationship Tab')]");
You can use the `ObjectAdmin#ENTRY_RELATIONSHIP_TAB` locator for this macro

2021-12-16 15:44 UTC, evanilson-santana commented
ci:forward

2021-12-16 15:44 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-12-16 15:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1612/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1612/jenkins-report.html">here</a>.</b></p>

2021-12-16 15:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/1079/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/1079/jenkins-report.html">here</a>.</b></p>

2021-12-16 15:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c04d47b24343ed4ce170a2db63de56b0c28e2f60">c04d47b24343ed4ce170a2db63de56b0c28e2f60</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/LPS-141652">LPS-141652</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/536829d414fc3618730ff18875a95814da58cdeb">536829d414fc3618730ff18875a95814da58cdeb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/1079/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/1079/jenkins-report.html">here</a>.</h5></details></html>

2021-12-16 15:49 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-28.liferay.com/job/test-portal-source-format/1079//consoleFull)

2021-12-16 15:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1612/">test-portal-acceptance-pullrequest(master)#1612</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1612/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1330">rodrigocunhaa#1330</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1591415566">[master] ci:test:relevant - PauloVAS &gt; rodrigocunhaa - PR#1330 - 2021-12-16[07:44:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/4979/">publish-testray-report#4979</a><br/></div></div>

2021-12-16 15:49 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/111248
[Console](https://test-1-28.liferay.com/job/test-portal-source-format/1079//consoleFull)

2021-12-16 15:49 UTC, closed without merging

2021-12-16 15:50 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/1079/">test-portal-source-format#1079</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/1079/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1330">rodrigocunhaa#1330</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1591417820">[master] ci:test:sf - PauloVAS &gt; rodrigocunhaa - PR#1330 - 2021-12-16[07:44:44]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/3746/">publish-testray-report#3746</a><br/></div></div>