LPS-141598
rodrigocunhaa/liferay-portal pull request #1366
Opened 2022-01-04 19:42 UTC by andreefarias

2022-01-04 19:42 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-01-04 19:43 UTC, andreefarias commented
ci:test:sf

2022-01-04 19:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-source-format/5292/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5292/jenkins-report.html">here</a>.</b></p>

2022-01-04 19:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/195958cbf07363d95346a14b8008358aa0a95eda">195958cbf07363d95346a14b8008358aa0a95eda</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LPS-141598">LPS-141598</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/9d9cfddcb087878be73604a0662475bd8eb84dfb">9d9cfddcb087878be73604a0662475bd8eb84dfb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-source-format/5292/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5292/jenkins-report.html">here</a>.</h5></details></html>

2022-01-04 19:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-4.liferay.com/job/test-portal-source-format/5292/">test-portal-source-format#5292</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5292/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1366">rodrigocunhaa#1366</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1596206539">[master] ci:test:sf - andreefarias &gt; rodrigocunhaa - PR#1366 - 2022-01-04[11:44:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-4.liferay.com/job/publish-testray-report/2548/">publish-testray-report#2548</a><br/></div></div>

2022-01-12 19:34 UTC, evanilson-santana requested changes
Hi @andreefarias 

Please, check my comments and let me know if you have any questions.

Thanks

2022-01-12 19:34 UTC, evanilson-santana commented on modules/apps/object/object-test/src/testFunctional/macros/ObjectAdmin.macro
> +
Hi @andreefarias 

You can use this macro: `assertObjectIsDisplayedOnControlPanel` that is in `objectPortlet.macro`

2022-01-12 19:34 UTC, evanilson-santana commented on modules/apps/object/object-test/src/testFunctional/tests/CreateObject.testcase
> +		ObjectAdmin.openObjectAdmin();
Hi @andreefarias 

You need to assert that your access to Object Admin is possible. You can validate this by checking if you have any objects created inside (by default it already has: `User` and `Commerce order`)

2022-01-12 21:18 UTC, andreefarias commented
ci:test:sf

2022-01-12 21:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-source-format/5297/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5297/jenkins-report.html">here</a>.</b></p>

2022-01-12 21:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bbc15974b01c164c902b37669ce408718e30b8cb">bbc15974b01c164c902b37669ce408718e30b8cb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LPS-141598">LPS-141598</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/adfa7933feb03c09fb8b0f25c3432d1123009392">adfa7933feb03c09fb8b0f25c3432d1123009392</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-source-format/5297/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5297/jenkins-report.html">here</a>.</h5></details></html>

2022-01-12 21:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-4.liferay.com/job/test-portal-source-format/5297/">test-portal-source-format#5297</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/5297/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1366">rodrigocunhaa#1366</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1599214827">[master] ci:test:sf - andreefarias &gt; rodrigocunhaa - PR#1366 - 2022-01-12[13:19:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-4.liferay.com/job/publish-testray-report/2562/">publish-testray-report#2562</a><br/></div></div>

2022-01-14 20:15 UTC, evanilson-santana approved these changes

2022-01-14 20:15 UTC, evanilson-santana commented
ci:forward

2022-01-14 20:15 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-01-14 20:15 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-01-14 20:16 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/forward-pullrequest/199//consoleFull)

2022-01-14 20:16 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/112179
[Console](https://test-1-25.liferay.com/job/forward-pullrequest/199//consoleFull)

2022-01-14 20:16 UTC, closed without merging