LPS-145718
rodrigocunhaa/liferay-portal pull request #1463
Opened 2022-01-24 21:02 UTC by andreefarias

2022-01-24 21:03 UTC, andreefarias commented
ci:test:sf

2022-01-24 21:04 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-01-24 21:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/1393/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1393/jenkins-report.html">here</a>.</b></p>

2022-01-24 21:17 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4576b994f149abdaadf7325acde465082a8023a1">4576b994f149abdaadf7325acde465082a8023a1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LPS-145718">LPS-145718</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/a1d5022514d9c84deed81191f2c3e68b40185fd9">a1d5022514d9c84deed81191f2c3e68b40185fd9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1393/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1393/jenkins-report.html">here</a>.</h5></details></html>

2022-01-24 21:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1393/">test-portal-source-format#1393</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1393/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1463">rodrigocunhaa#1463</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1603367117">[master] ci:test:sf - andreefarias &gt; rodrigocunhaa - PR#1463 - 2022-01-24[13:14:13]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/4529/">publish-testray-report#4529</a><br/></div></div>

2022-01-25 17:13 UTC, rodrigocunhaa requested changes
Hi @andreefarias ,

Please, check my comments and make the necessary changes. Thanks!

2022-01-25 17:13 UTC, rodrigocunhaa commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectActions.testcase
> +		ObjectAdmin.deleteActionViaUI(actionName = "Action Name");
After you delete, you have to also assert that the Action is not present.

2022-01-25 19:16 UTC, andreefarias commented
ci:test:sf

2022-01-25 19:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1208/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1208/jenkins-report.html">here</a>.</b></p>

2022-01-25 19:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7d3bcdbd60db1363264b15dddd59ed46121d86ac">7d3bcdbd60db1363264b15dddd59ed46121d86ac</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LPS-145718">LPS-145718</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/49591b0b91483ce866f9d3c6c8197c0d2e22004e">49591b0b91483ce866f9d3c6c8197c0d2e22004e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1208/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1208/jenkins-report.html">here</a>.</h5></details></html>

2022-01-25 19:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1208/">test-portal-source-format#1208</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1208/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1463">rodrigocunhaa#1463</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1603821322">[master] ci:test:sf - andreefarias &gt; rodrigocunhaa - PR#1463 - 2022-01-25[11:16:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/4116/">publish-testray-report#4116</a><br/></div></div>

2022-01-25 19:28 UTC, rodrigocunhaa commented
ci:forward

2022-01-25 19:28 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-01-25 19:28 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-01-25 19:29 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-25.liferay.com/job/forward-pullrequest/218//consoleFull)

2022-01-25 19:29 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/112613
[Console](https://test-1-25.liferay.com/job/forward-pullrequest/218//consoleFull)

2022-01-25 19:29 UTC, closed without merging