LPS-146873
rodrigocunhaa/liferay-portal pull request #1555
Opened 2022-02-08 19:42 UTC by andreefarias

2022-02-08 19:42 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-02-08 19:43 UTC, andreefarias commented
ci:test:sf

2022-02-08 19:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/742/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/742/jenkins-report.html">here</a>.</b></p>

2022-02-08 19:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/153a6ed2eb883aa3253e133486f0fabf43c1fdf7">153a6ed2eb883aa3253e133486f0fabf43c1fdf7</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LPS-146873">LPS-146873</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/07f05c38e849162afd7f8fb2cbdb824cf18e2d25">07f05c38e849162afd7f8fb2cbdb824cf18e2d25</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-34.liferay.com/job/test-portal-source-format/742/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/742/jenkins-report.html">here</a>.</h5></details></html>

2022-02-08 19:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/742/">test-portal-source-format#742</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/742/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1555">rodrigocunhaa#1555</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1609143778">[master] ci:test:sf - andreefarias &gt; rodrigocunhaa - PR#1555 - 2022-02-08[11:43:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/2549/">publish-testray-report#2549</a><br/></div></div>

2022-02-08 19:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/742/">test-portal-source-format#742</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/742/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1555">rodrigocunhaa#1555</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1609143778">[master] ci:test:sf - andreefarias &gt; rodrigocunhaa - PR#1555 - 2022-02-08[11:43:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/2550/">publish-testray-report#2550</a><br/></div></div>

2022-02-10 18:09 UTC, evanilson-santana requested changes
Hi @andreefarias 

Please, check my comments and make the necessary changes.

Thanks

2022-02-10 18:09 UTC, evanilson-santana commented on modules/apps/object/object-test/src/testFunctional/tests/ObjectWorkflow.testcase
> +			objectName = "CustomObject");
Hi @andreefarias 

You can add the parameter `fieldBusinessType = "Text"` ? 

thanks

2022-02-10 18:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b6164899f2d245d0367d43b5d133e73e8be92ff9">b6164899f2d245d0367d43b5d133e73e8be92ff9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LPS-146873">LPS-146873</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/50188712fa914bf46264a2a41bccc85ccb05baa0">50188712fa914bf46264a2a41bccc85ccb05baa0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/921/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/921/jenkins-report.html">here</a>.</h5></details></html>

2022-02-10 18:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/921/">test-portal-source-format#921</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/921/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1555">rodrigocunhaa#1555</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1609976870">[master] ci:test:sf - andreefarias &gt; rodrigocunhaa - PR#1555 - 2022-02-10[10:43:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/2393/">publish-testray-report#2393</a><br/></div></div>

2022-02-10 18:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/921/">test-portal-source-format#921</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/921/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1555">rodrigocunhaa#1555</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1609976870">[master] ci:test:sf - andreefarias &gt; rodrigocunhaa - PR#1555 - 2022-02-10[10:43:19]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/2394/">publish-testray-report#2394</a><br/></div></div>

2022-02-10 20:57 UTC, evanilson-santana approved these changes

2022-02-10 21:00 UTC, evanilson-santana commented
ci:forward

2022-02-10 21:02 UTC, closed without merging