LPS-147871
rodrigocunhaa/liferay-portal pull request #1639
Opened 2022-02-25 22:30 UTC by andreefarias

2022-02-25 22:30 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-02-25 22:30 UTC, andreefarias commented
ci:test:sf

2022-02-25 22:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/1685/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1685/jenkins-report.html">here</a>.</b></p>

2022-02-25 22:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/32e5e6e8e955c385cb626095e1b2098b85c0a814">32e5e6e8e955c385cb626095e1b2098b85c0a814</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/andreefarias/liferay-portal/tree/LPS-147871">LPS-147871</a><br/>Branch GIT ID: <a href="https://github.com/andreefarias/liferay-portal/commit/fc30419038faa31e1f173ccbb39d748089348af6">fc30419038faa31e1f173ccbb39d748089348af6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1685/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1685/jenkins-report.html">here</a>.</h5></details></html>

2022-02-25 22:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/1685/">test-portal-source-format#1685</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/1685/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/1639">rodrigocunhaa#1639</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1620026030">[master] ci:test:sf - andreefarias &gt; rodrigocunhaa - PR#1639 - 2022-02-25[14:30:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/5773/">publish-testray-report#5773</a><br/></div></div>

2022-03-03 09:59 UTC, rodrigocunhaa requested changes
Hi @andreefarias , you mixed the tests. This one you are validating on the Layout and on the https://github.com/rodrigocunhaa/liferay-portal/pull/1638 you are validating on the View.

2022-03-03 17:15 UTC, closed without merging