LRQA 60671 | master
rodrigocunhaa/liferay-portal pull request #203
Opened 2020-10-16 19:04 UTC by calvinctvo

https://issues.liferay.com/browse/LRQA-60671

2020-10-16 19:04 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-10-16 19:05 UTC, calvinctvo commented
ci:test:sf

2020-10-16 19:05 UTC, calvinctvo commented
ci:test:relevant

2020-10-16 19:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/2663/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com//userContent/jobs/test-portal-source-format/builds/2663/jenkins-report.html">here</a>.</b></p>

2020-10-16 19:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/7370/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7370/jenkins-report.html">here</a>.</b></p>

2020-10-16 19:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a9237c529f4d19ec103ecd5652c70c9de47cada4">a9237c529f4d19ec103ecd5652c70c9de47cada4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/calvinctvo/liferay-portal/tree/LRQA-60671">LRQA-60671</a><br/>Branch GIT ID: <a href="https://github.com/calvinctvo/liferay-portal/commit/fd7312cd37b3a0b2272fb4e4c178f14f53b23427">fd7312cd37b3a0b2272fb4e4c178f14f53b23427</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/2663/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/2663/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./modules/apps/app-builder/app-builder-test/src/testFunctional/macros/FormViewBuilder.macro expected:&lt;... goToFieldsetsTab \{
     [java] []		Click(locator1 = "...&gt; but was:&lt;... goToFieldsetsTab \{
     [java] [
     [java] ]		Click(locator1 = "...&gt;
     [java] 2: ./modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase expected:&lt;...= "Text");
     [java] 
     [java] 		Click([locator1 = "FormViewBuilder#RULE_BUILDER_GO_BACK");
     [java] 
     [java] 		FormViewBuilder.setUpTwoFieldSets(
     [java] 			fieldSetName = "Field Sets",
     [java] 			fieldType = "Text",
     [java] 			fieldType2 = "Numeric");
     [java] 
     [java] 		FormViewBuilder.goToFieldsetsTab();
     [java] 
     [java] 		FormViewBuilder.addFieldByDoubleClick(fieldType = "Field Sets");
     [java] 
     [java] 		FormViewBuilder.setName(formViewName = "Fields from Fieldsets");
     [java] 
     [java] 		FormViewBuilder.validateFieldLabel(fieldLabel = "Field Sets");
     [java] 
     [java] 		FormViewBuilder.save();
     [java] 
     [java] 		AppBuilderAdmin.openItem(itemName = "Fields from Fieldsets");
     [java] 
     [java] 		FormViewBuilder.goToFieldsetsTab();
     [java] 
     [java] 		TableViewBuilder.validateDisabledField(fieldType = "Field Sets");
     [java] 	\}]
     [java] 
     [java] \}&gt; but was:&lt;...= "Text");
     [java] 
     [java] 		Click([
     [java] 			locator1 = "FormViewBuilder#RULE_BUILDER_GO_BACK");
     [java] 
     [java] 		FormViewBuilder.setUpTwoFieldSets(
     [java] 			fieldType = "Text",
     [java] 			fieldSetName = "Field Sets",
     [java] 			fieldType2 = "Numeric");
     [java] 
     [java] 		FormViewBuilder.goToFieldsetsTab();
     [java] 
     [java] 		FormViewBuilder.addFieldByDoubleClick(fieldType = "Field Sets");
     [java] 
     [java] 		FormViewBuilder.setName(formViewName = "Fields from Fieldsets");
     [java] 
     [java] 		FormViewBuilder.validateFieldLabel(fieldLabel = "Field Sets");
     [java] 
     [java] 		FormViewBuilder.save();
     [java] 
     [java] 		AppBuilderAdmin.openItem(itemName = "Fields from Fieldsets");
     [java] 
     [java] 		FormViewBuilder.goToFieldsetsTab();
     [java] 
     [java] 		TableViewBuilder.validateDisabledField(fieldType = "Field Sets");
     [java] 
     [java] 	\}
     [java] ]
     [java] 
     [java] \}&gt;
     [java] </code></pre></details></html>

2020-10-16 19:24 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/test-portal-source-format/2663/">test-portal-source-format#2663</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/2663/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/203">rodrigocunhaa#203</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/51347.aspx">master - calvinctvo > rodrigocunhaa - PR#203 - 2020-10-16[12:05:26]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/publish-spira-report/6507/">publish-spira-report#6507</a><br />

2020-10-16 20:49 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 14 out of 14 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 48 out of 48 jobs passed in 2 hours 12 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/44c022b894f3e185233fc56e7270ba92d70079fe">44c022b894f3e185233fc56e7270ba92d70079fe</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/27bc57847a0fbdd19ff9c855a0e2eda43d622c23">27bc57847a0fbdd19ff9c855a0e2eda43d622c23</a></p><details><summary><strong>ci:test:stable - 14 out of 14 jobs PASSED</strong></summary><details><summary><strong>14 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451127/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473841/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423486/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/1</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/337444/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/2</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/364644/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473840/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/4</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443073/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/5</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423485/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/316816/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423487/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/366635/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/404520/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451130/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/413020/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 48 out of 48 jobs PASSED</strong></summary><details><summary><strong>48 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/7370/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/473838/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/364645/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451127/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451986/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/404522/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/445657/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/10</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/450561/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/11</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451131/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/12</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/306457/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/13</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/413473/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/14</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451985/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/15</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/203404/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/440807/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/316815/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/404521/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/337443/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/203403/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/7</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/306456/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/8</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/413472/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/9</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/306455/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql [...]

2020-10-16 20:51 UTC, calvinctvo commented
ci:test:sf

2020-10-16 20:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-source-format/3503/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-portal-source-format/builds/3503/jenkins-report.html">here</a>.</b></p>

2020-10-16 20:55 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 0 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a9237c529f4d19ec103ecd5652c70c9de47cada4">a9237c529f4d19ec103ecd5652c70c9de47cada4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/calvinctvo/liferay-portal/tree/LRQA-60671">LRQA-60671</a><br/>Branch GIT ID: <a href="https://github.com/calvinctvo/liferay-portal/commit/3bb48fd2d968bee994c1f7671f17afce30e29621">3bb48fd2d968bee994c1f7671f17afce30e29621</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-source-format/3503/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/3503/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/app-builder/app-builder-test/src/testFunctional/macros/FormViewBuilder.macro expected:&lt;... goToFieldsetsTab \{
     [java] []		Click(locator1 = "...&gt; but was:&lt;... goToFieldsetsTab \{
     [java] [
     [java] ]		Click(locator1 = "...&gt;
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:457)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:276)
[stopwatch] [run.batch.test.action: 1:09.839 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:583: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:717: Java returned: 1
      [get] Getting: http://test-1-4/job/test-portal-source-format/3503//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20201016132910644.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20201016132910644.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null31057112.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1384980095
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 188ms
[junitreport] Deleting: /tmp/null1384980095
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 10-16-2020 13:29:15:846 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
     [echo] 
     [echo] Ant GC log:
     [echo] 
     [echo] Java HotSpot(TM) 64-Bit Server VM (25.121-b13) for linux-amd64 JRE (1.8.0_121-b13), built on Dec 12 2016 16:36:53 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)</code></pre></details></html>

2020-10-16 20:56 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/7370/">test-portal-acceptance-pullrequest(master)#7370</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-16.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7370/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/203">rodrigocunhaa#203</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1312.aspx">/Liferay DXP 7.3/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/51397.aspx">master - calvinctvo > rodrigocunhaa - PR#203 - 2020-10-16[12:05:29]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/publish-spira-report/6612/">publish-spira-report#6612</a><br />

2020-10-16 21:01 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-4.liferay.com/job/test-portal-source-format/3503/">test-portal-source-format#3503</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/3503/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/203">rodrigocunhaa#203</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/51401.aspx">master - calvinctvo > rodrigocunhaa - PR#203 - 2020-10-16[13:52:17]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-4.liferay.com/job/publish-spira-report/7576/">publish-spira-report#7576</a><br />

2020-10-28 20:57 UTC, rodrigocunhaa commented
Just started reviewing :)

2020-10-28 21:23 UTC, rodrigocunhaa requested changes
Hi @calvinctvo , please, make the changes that I mentioned. Thanks!

2020-10-28 21:23 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +		Click(locator1 = "FormViewBuilder#RULE_BUILDER_GO_BACK");
Hi @calvinctvo , you can remove this code. There is no need to add a regular field since the tests are for fieldset only.

2020-10-28 21:23 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +		FormViewBuilder.validateFieldLabel(fieldLabel = "Field Sets");
Hi @calvinctvo , you can remove this part of the code. There is no need to validate that since it is being already covered by another test.

2020-10-28 21:23 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +		TableViewBuilder.validateDisabledField(fieldType = "Field Sets");
Hi @calvinctvo , after you save the Form View, you have to go the the "Table Views" tab and select to create a new Table. After that you will validate the following scenarios:
- All fields from the fieldset are displayed and available
- Add a field by drag-drop and also by double-clicking
- Remove a field from Table View

2020-10-28 21:25 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +		TableViewBuilder.validateDisabledField(fieldType = "Field Sets");
Also, remember to run the format source command to fix the sf issue.

2020-10-28 21:28 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +		property test.name.skip.portal.instance = "AppBuilder#ViewFieldSetsInTableView";
I forgot to mention that you can remove this line of code as well. There is no need to skip the virtual instance for this test.

2020-10-28 21:30 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +		property test.name.skip.portal.instance = "AppBuilder#ViewFieldSetsInTableView";
I forgot to mention that you can remove this line of code as well. There is no need to skip virtual instance for this test. Thanks!

2020-11-03 20:45 UTC, rodrigocunhaa commented
Just started reviewing :)

2020-11-03 21:43 UTC, rodrigocunhaa commented
Great job @calvinctvo. I was having a hard time to fix the conflicts so I created a new branch and made all changes there:
https://github.com/rodrigocunhaa/liferay-portal/pull/214

Keep up the good work!

2020-11-03 21:43 UTC, closed without merging