LRQA-60725
rodrigocunhaa/liferay-portal pull request #204
Opened 2020-10-22 16:41 UTC by nkkwon

https://issues.liferay.com/browse/LRQA-60725

2020-10-22 16:41 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-10-22 16:41 UTC, nkkwon commented
ci:test:sf

2020-10-22 16:41 UTC, nkkwon commented
ci:test:relevant

2020-10-22 16:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/4678/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com//userContent/jobs/test-portal-source-format/builds/4678/jenkins-report.html">here</a>.</b></p>

2020-10-22 16:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest(master)/6734/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6734/jenkins-report.html">here</a>.</b></p>

2020-10-22 16:44 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/553ad541994356738540b98a64b36f55bc3a6036">553ad541994356738540b98a64b36f55bc3a6036</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/nkkwon/liferay-portal/tree/LRQA-60725">LRQA-60725</a><br/>Branch GIT ID: <a href="https://github.com/nkkwon/liferay-portal/commit/d05c555cbcf7eb66d040572af5211327eeda8427">d05c555cbcf7eb66d040572af5211327eeda8427</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/4678/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/4678/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/app-builder/app-builder-test/src/testFunctional/macros/FormViewBuilder.macro expected:&lt;... goToFieldsetsTab \{
     [java] []		Click(locator1 = "...&gt; but was:&lt;... goToFieldsetsTab \{
     [java] [
     [java] ]		Click(locator1 = "...&gt;
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:457)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:276)
[stopwatch] [run.batch.test.action: 1:27.151 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:583: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:717: Java returned: 1
      [get] Getting: http://test-1-19/job/test-portal-source-format/4678//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20201022094424799.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20201022094424799.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1078540629.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null234924206
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 188ms
[junitreport] Deleting: /tmp/null234924206
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 10-22-2020 09:44:30:466 PDT
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
     [echo] 
     [echo] Ant GC log:
     [echo] 
     [echo] Java HotSpot(TM) 64-Bit Server VM (25.121-b13) for linux-amd64 JRE (1.8.0_121-b13), built on Dec 12 2016 16:36:53 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)</code></pre></details></html>

2020-10-22 16:46 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-19.liferay.com/job/test-portal-source-format/4678/">test-portal-source-format#4678</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/4678/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/204">rodrigocunhaa#204</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/53167.aspx">master - nkkwon > rodrigocunhaa - PR#204 - 2020-10-22[09:41:46]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/11727/">publish-spira-report#11727</a><br />

2020-10-22 16:59 UTC, nkkwon commented
ci:test:sf

2020-10-22 17:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/4297/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-portal-source-format/builds/4297/jenkins-report.html">here</a>.</b></p>

2020-10-22 17:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/553ad541994356738540b98a64b36f55bc3a6036">553ad541994356738540b98a64b36f55bc3a6036</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/nkkwon/liferay-portal/tree/LRQA-60725">LRQA-60725</a><br/>Branch GIT ID: <a href="https://github.com/nkkwon/liferay-portal/commit/05b512fec6f15ac4c169eb975cd5c1815061b8b8">05b512fec6f15ac4c169eb975cd5c1815061b8b8</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/4297/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/4297/jenkins-report.html">here</a>.</h5></details></html>

2020-10-22 17:04 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-6.liferay.com/job/test-portal-source-format/4297/">test-portal-source-format#4297</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/4297/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/204">rodrigocunhaa#204</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/53173.aspx">master - nkkwon > rodrigocunhaa - PR#204 - 2020-10-22[09:59:58]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-4.liferay.com/job/publish-spira-report/7903/">publish-spira-report#7903</a><br />

2020-10-22 18:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 14 out of 14 jobs passed</h3><h3>:x: ci:test:relevant - 45 out of 47 jobs passed in 2 hours</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/553ad541994356738540b98a64b36f55bc3a6036">553ad541994356738540b98a64b36f55bc3a6036</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/27bc57847a0fbdd19ff9c855a0e2eda43d622c23">27bc57847a0fbdd19ff9c855a0e2eda43d622c23</a></p><details><summary><strong>ci:test:stable - 14 out of 14 jobs PASSED</strong></summary><details><summary><strong>14 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443836/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/312820/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/453416/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/1</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/442078/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/2</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/414465/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/3</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/452816/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/4</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/394102/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/5</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/312818/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443843/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443844/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/442079/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/312817/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443842/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/308252/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 45 out of 47 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest(master)/6734/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443839/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8</strong></strike></a></li></ul></div><details><summary><strong>45 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443838/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/466257/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443836/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/415035/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/452817/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/453417/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/10</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/366091/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/11</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475378/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/12</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/414466/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/13</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/366090/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/14</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444293/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/368200/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/3</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/442077/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/4</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444292/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/5</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/453415/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/6</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/366089/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/7</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/368199/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/8</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443840/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/9</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/443841/" [...]

2020-10-22 18:45 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest(master)/6734/">test-portal-acceptance-pullrequest(master)#6734</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6734/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/204">rodrigocunhaa#204</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1312.aspx">/Liferay DXP 7.3/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/53213.aspx">master - nkkwon > rodrigocunhaa - PR#204 - 2020-10-22[09:41:46]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-20.liferay.com/job/publish-spira-report/6127/">publish-spira-report#6127</a><br />

2020-10-26 19:37 UTC, nkkwon commented
ci:test:appbuilder

2020-10-26 19:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest(master)/6783/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6783/jenkins-report.html">here</a>.</b></p>

2020-10-26 19:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:appbuilder - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0f9ecfe6f40a29fefbd4e7a2d78c74e2504636d1">0f9ecfe6f40a29fefbd4e7a2d78c74e2504636d1</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/424ab1158c689b11bc409031cffca77c71b5b194">424ab1158c689b11bc409031cffca77c71b5b194</a></p><details><summary><strong>ci:test:appbuilder - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest(master)/6783/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6783/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest(master)/6783/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>The CI test suite 'appbuilder' is not a valid test suite.

List of available CI test suites:
* acceptance
* acceptance-upstream
* accounts
* analytics-cloud
* app-builder
* autotagging
* backend
* backend-hypersonic
* blade
* blogs
* bulkediting
* bundle
* calendar
* clustering
* commerce
* contentpagereview
* data-engine
* depot
* dlstore
* documents
* dummy
* echo
* echo-acceptance
* environments
* environments-alpine3
* environments-centos6
* environments-centos8
* environments-debian7
* environments-debian8
* environments-debian9
* environments-oracle19
* environments-orcllinux6
* environments-orcllinux7
* environments-postgresql11
* environments-release-ce
* environments-release-dxp
* environments-suse15
* environments-ubuntu14
* environments-ubuntu16
* environments-ubuntu18
* export-import
* forms
* frontend
* gauntlet
* gradle-plugins
* headless
* headless-acceptance
* jdk11
* jsf
* knowledgebase
* ldap
* license
* lima
* lpkg
* messageboards
* oauth2
* onedrive
* onlineediting
* poshi
* poshi-gauntlet
* project-templates
* publications
* redirect
* relevant
* roles
* saml
* search
* search-jdk11
* search-solr
* security
* seo
* sf
* sharepoint
* sharing
* site-template
* solr
* stable
* staging
* tango
* tango-acceptance
* tango-analytics-cloud
* tck
* translations
* upgrade
* upgrade-client
* users
* wiki
* workflow
* workflow-es7

</p><p>Comment 'ci:help' for details.</p></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2020-10-26 19:42 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest(master)/6783/">test-portal-acceptance-pullrequest(master)#6783</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6783/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> appbuilder<br /><strong>Pull Request:</strong><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/204">rodrigocunhaa#204</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1922.aspx">/Liferay DXP 7.3/Pull Request/ci:test:appbuilder</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/54123.aspx">master - nkkwon > rodrigocunhaa - PR#204 - 2020-10-26[12:38:12]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/publish-spira-report/6967/">publish-spira-report#6967</a><br />

2020-10-28 22:20 UTC, rodrigocunhaa requested changes
Hi @nkkwon , please, make the changes that I requested. Thanks!

2020-10-28 22:20 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +		FormViewBuilder.validateFieldLabel(fieldLabel = "Text");
Hi @nkkwon , you can remove this part of the code since there is no need to add a regular field for this scenarios.

2020-10-28 22:20 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +			selectAction = "Delete");
Hi @nkkwon , after deleting a fieldset, you need to assert that the fieldset is no longer present.

2020-10-28 22:20 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +			selectAction = "Delete");
Hi @nkkwon , same thing here, you need to assert that the fieldset is no longer present.

2020-10-28 22:20 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +			selectAction = "Delete");
Hi @nkkwon , same thing here, you need to assert that the fieldset is no longer present.

2020-10-28 22:20 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +			selectAction = "Delete");
Hi @nkkwon , same thing here, you have to assert that the fieldset is no longer present.

2020-10-28 22:20 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +			selectAction = "Delete");
Hi @nkkwon , same thing here, you need to assert that the fieldset is no longer present.

2020-10-28 22:20 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +		AppBuilderAdmin.gotoCustomAppApplicationsMenuApplications(portlet = "App One");
Hi @nkkwon , after you go to the App, assert something on the screen that belongs to the App so you can make sure that no crash happened when accessing the App.

2020-10-28 22:20 UTC, rodrigocunhaa commented on modules/apps/app-builder/app-builder-test/src/testFunctional/tests/AppBuilder.testcase
> +			fieldType = "Text",
Hi @nkkwon , change this variabel to `fieldType1`

2020-11-13 22:06 UTC, rodrigocunhaa approved these changes

2020-11-13 22:07 UTC, rodrigocunhaa commented
Great job @nkkwon , it looks good to me now. Thank you!

2020-11-13 22:07 UTC, rodrigocunhaa commented
ci:test:sf

2020-11-13 22:07 UTC, rodrigocunhaa commented
ci:test:relevant

2020-11-13 22:07 UTC, rodrigocunhaa commented
ci:test:app-builder

2020-11-13 22:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/4442/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-portal-source-format/builds/4442/jenkins-report.html">here</a>.</b></p>

2020-11-13 22:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/7513/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7513/jenkins-report.html">here</a>.</b></p>

2020-11-13 22:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest(master)/6858/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-17.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6858/jenkins-report.html">here</a>.</b></p>

2020-11-13 22:08 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 0 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7eec3e0230452ffd9b03e77b0ebf877266b92a1b">7eec3e0230452ffd9b03e77b0ebf877266b92a1b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/nkkwon/liferay-portal/tree/LRQA-60725">LRQA-60725</a><br/>Branch GIT ID: <a href="https://github.com/nkkwon/liferay-portal/commit/f23be3938a50dd4a01d67defc7de9c596d988b63">f23be3938a50dd4a01d67defc7de9c596d988b63</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/4442/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/4442/jenkins-report.html">here</a>.</h5><div><p>Please fix <strong>rebase errors</strong> on <strong><a href="https://github.com/nkkwon/liferay-portal/tree/LRQA-60725">nkkwon/LRQA-60725</a></strong><pre><code>Target exception: java.lang.RuntimeException: Unable to rebase nkkwon-204-LRQA-60725 to master
error: Failed to merge in the changes.</code></pre></p></div></details></html>

2020-11-13 22:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:app-builder - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/61640de358d83c5bfa8c051a2969a0f4521080e1">61640de358d83c5bfa8c051a2969a0f4521080e1</a></p><details><summary><strong>ci:test:app-builder - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/7513/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7513/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/7513/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>Please fix <strong>rebase errors</strong> on <strong><a href="https://github.com/nkkwon/liferay-portal/tree/LRQA-60725">nkkwon/LRQA-60725</a></strong><pre><code>[beanshell] java.lang.RuntimeException: Unable to rebase cache-rodrigocunhaa-61640de358d83c5bfa8c051a2969a0f4521080e1-nkkwon-f23be3938a50dd4a01d67defc7de9c596d988b63 to master
[beanshell] error: Failed to merge in the changes.</code></pre></p></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2020-11-13 22:10 UTC, rodrigocunhaa commented
ci:stop

2020-11-13 22:10 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-6.liferay.com/job/test-portal-source-format/4442/">test-portal-source-format#4442</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/4442/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/204">rodrigocunhaa#204</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/60947.aspx">master - nkkwon > rodrigocunhaa - PR#204 - 2020-11-13[14:07:42]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/13680/">publish-spira-report#13680</a><br />

2020-11-13 22:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/61640de358d83c5bfa8c051a2969a0f4521080e1">61640de358d83c5bfa8c051a2969a0f4521080e1</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest(master)/6858/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-17.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6858/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest(master)/6858/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>Build was aborted</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2020-11-13 22:11 UTC, rodrigocunhaa commented
Just started reviewing :)

2020-11-13 22:17 UTC, rodrigocunhaa commented
Fixed conflicts here: https://github.com/rodrigocunhaa/liferay-portal/pull/220

2020-11-13 22:17 UTC, closed without merging