LRQA-67516
rodrigocunhaa/liferay-portal pull request #396
Opened 2021-06-04 20:09 UTC by rafaellajordao

2021-06-04 20:51 UTC, pedro-michel commented
ci:test:sf

2021-06-04 20:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/644/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/644/jenkins-report.html">here</a>.</b></p>

2021-06-04 20:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a0eaa844bd39ac21ea9dca10ddcba4a9d9ca3338">a0eaa844bd39ac21ea9dca10ddcba4a9d9ca3338</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/rafaellajordao/liferay-portal/tree/LRQA-67516">LRQA-67516</a><br/>Branch GIT ID: <a href="https://github.com/rafaellajordao/liferay-portal/commit/740a9c162488dedc3b1a95ecb9c2a796198d78b0">740a9c162488dedc3b1a95ecb9c2a796198d78b0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/644/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/644/jenkins-report.html">here</a>.</h5></details></html>

2021-06-04 20:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/644/">test-portal-source-format#644</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/644/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/396">rodrigocunhaa#396</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1537734772">[master] ci:test:sf - rafaellajordao &gt; rodrigocunhaa - PR#396 - 2021-06-04[13:51:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/1834/">publish-testray-report#1834</a><br/></div></div>

2021-06-07 22:10 UTC, rodrigocunhaa requested changes
Hi @rafaellajordao ,

For this test, you need to verify the message that appears when there is no Workflow available. So, you have to do the following:

1. Delete Single Approver workflow
2. Access Metrics page
3. Assert that the "No Current Metrics" and "Once there are active processes, metrics will appear here." messages are displayed

Tip: You will need to use the `deleteWorkflowDefinition` macro from `Workflow.macro`.

2021-06-08 14:48 UTC, rafaellajordao commented
Fixed! @rodrigocunhaa

2021-06-08 23:08 UTC, closed without merging