LRQA-67888
rodrigocunhaa/liferay-portal pull request #426
Opened 2021-06-08 21:45 UTC by evanilson-santana

2021-06-08 21:45 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-06-09 12:23 UTC, anabuchmann commented
ci:test:sf

2021-06-09 12:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/625/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-source-format/builds/625/jenkins-report.html">here</a>.</b></p>

2021-06-09 12:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a0de1166dd81ef9cfd22f8c3cae1066483049425">a0de1166dd81ef9cfd22f8c3cae1066483049425</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LRQA-67888">LRQA-67888</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/6df166df176cb5eea7b91722ce833afcbcc06fbf">6df166df176cb5eea7b91722ce833afcbcc06fbf</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/625/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/625/jenkins-report.html">here</a>.</h5></details></html>

2021-06-09 12:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/625/">test-portal-source-format#625</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/625/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/426">rodrigocunhaa#426</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1538810221">[master] ci:test:sf - evanilson-santana &gt; rodrigocunhaa - PR#426 - 2021-06-09[05:23:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/1236/">publish-testray-report#1236</a><br/></div></div>

2021-06-09 13:42 UTC, anabuchmann requested changes
Hi @evanilson-santana !
Could you, please, check my comments and make the changes that I requested?
Thank you!

2021-06-09 13:42 UTC, anabuchmann commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/tests/WorkflowMetricsPerformanceByStep.testcase
> +	@description = "LPS-100674 - Verify that the card (Performance by Steps) works as designed when the portal is set to a non-en-US locale"
Please, remove the parenthesis from (Performance by Step).
When, in the test map, you have double quotation marks in the test case description, you can only remove them from the stub description.

2021-06-09 13:42 UTC, anabuchmann commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/tests/WorkflowMetricsPerformanceByStep.testcase
> +	@description = "LPS-100674 - Verify that when the user selects (Last 90 Days) time period the result and filter options displayed in accordance with reference"
Please, remove the parenthesis from (Last 90 Days).
When, in the test map, you have double quotation marks in the test case description, you can only remove them from the stub description.

2021-06-09 13:42 UTC, anabuchmann commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/tests/WorkflowMetricsPerformanceByStep.testcase
> +	@description = "LPS-100674 - Verify that when the user selects (Last 180 Days) time period the result and filter options are displayed in accordance with reference"
Please, remove the parenthesis from (Last 180 Days).
When, in the test map, you have double quotation marks in the test case description, you can only remove them from the stub description.

2021-06-09 13:42 UTC, anabuchmann commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/tests/WorkflowMetricsPerformanceByStep.testcase
> +	@description = "LPS-100674 - Verify that when the user selects (Last Year) time period the result and filter options displayed in accordance with reference"
Please, remove the parenthesis from (Last Year).
When, in the test map, you have double quotation marks in the test case description, you can only remove them from the stub description.

2021-06-09 13:42 UTC, anabuchmann commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/tests/WorkflowMetricsPerformanceByStep.testcase
> +	test FromAndToAreRequiredFields {
Please, in description, change the LPS number for 100674.

2021-06-09 13:42 UTC, anabuchmann commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/tests/WorkflowMetricsPerformanceByStep.testcase
> +	@description = "LPS-100674 - Verify that hovering the info icon next to (Performance by Step) card will display a tooltip"
Please, remove the parenthesis from (Perfomance by Step).
When, in the test map, you have double quotation marks in the test case description, you can only remove them from the stub description.

2021-06-09 13:42 UTC, anabuchmann commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/tests/WorkflowMetricsPerformanceByStep.testcase
> +	@description = "LPS-100677 - Verify that the search is an approximate match (aka (LIKE) search type or (character by character comparison))"
Please, remove the parenthesis from (LIKE) and (character by character comparison).
When, in the test map, you have double quotation marks in the test case description, you can only remove them from the stub description.

2021-06-09 13:42 UTC, anabuchmann commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/tests/WorkflowMetricsPerformanceByStep.testcase
> +	@description = "LPS-97667 - Verify that, when displaying time, the time units are shortened by using the biggest measurement possible, and use up to 2 units per time, with (minute) as smallest value
Please, remove the parenthesis from (minute) and (days).
When, in the test map, you have double quotation marks in the test case description, you can only remove them from the stub description.

2021-06-09 13:42 UTC, anabuchmann commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/tests/WorkflowMetricsPerformanceByStep.testcase
> +	@description = "LPS-100674 - Verify that the card (Performance by Step), when it has 6 or more entries, the table should provide a vertical scroll"
Please, remove the parenthesis from (Performance by Step)
When, in the test map, you have double quotation marks in the test case description, you can only remove them from the stub description.

2021-06-09 13:42 UTC, anabuchmann commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/tests/WorkflowMetricsPerformanceByStep.testcase
> +	@description = "LPS-100674 - Verify that the card (Performance by Step), when it has 5 or fewer entries, the table should not scroll"
Please, remove the parenthesis from (Performance by Step)
When, in the test map, you have double quotation marks in the test case description, you can only remove them from the stub description.

2021-06-09 13:42 UTC, anabuchmann commented on modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional/tests/WorkflowMetricsPerformanceByStep.testcase
> +	@description = "LPS-100674 - Verify that when an SLA is deleted, the data in (Performance by Step) is still part of the average calculation"
Please, remove the parenthesis from (Performance by Step)
When, in the test map, you have double quotation marks in the test case description, you can only remove them from the stub description.

2021-06-10 14:05 UTC, rodrigocunhaa commented
Just started reviewing :)

2021-06-10 14:07 UTC, rodrigocunhaa commented
Hi @evanilson-santana ,

Thank you for your commit.

There was only one LPS number to fix, but I did it here: https://github.com/rodrigocunhaa/liferay-portal/pull/441

2021-06-10 14:07 UTC, closed without merging