LRQA-67806
rodrigocunhaa/liferay-portal pull request #460
Opened 2021-06-14 21:51 UTC by PauloVAS

2021-06-14 21:51 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-06-14 21:57 UTC, PauloVAS commented
ci:test:sf

2021-06-14 21:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1148/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/1148/jenkins-report.html">here</a>.</b></p>

2021-06-14 21:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d9ae01826a377988429553ad6025617a2013b514">d9ae01826a377988429553ad6025617a2013b514</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/LRQA-67806">LRQA-67806</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/08e098d7705130d8312bc93aa96eb52cb26a5c13">08e098d7705130d8312bc93aa96eb52cb26a5c13</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1148/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1148/jenkins-report.html">here</a>.</h5></details></html>

2021-06-14 22:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1148/">test-portal-source-format#1148</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1148/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/460">rodrigocunhaa#460</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1540074808">[master] ci:test:sf - PauloVAS &gt; rodrigocunhaa - PR#460 - 2021-06-14[14:57:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/3443/">publish-testray-report#3443</a><br/></div></div>

2021-06-18 15:56 UTC, rodrigocunhaa requested changes
Hi @PauloVAS, could you please make the changes that I requested?

Thanks!

2021-06-18 15:56 UTC, rodrigocunhaa commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/WorkflowMetricsAllItemsListTransitionTasks.testcase
> +		property portal.acceptance = "true";
You can remove this property

2021-06-18 15:56 UTC, rodrigocunhaa commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/WorkflowMetricsAllItemsListTransitionTasks.testcase
> +			entryTitle = "Test Blogs 2");
Add the blogs through API. Do the following:

```suggestion
		JSONBlog.addEntry(
                      entryContent = "Blogs Entry Content",
                      entryTitle = "Blogs Entry Title 1");
                  
              JSONBlog.addEntry(
                      entryContent = "Blogs Entry Content",
                      entryTitle = "Blogs Entry Title 2");
```

2021-06-18 15:56 UTC, rodrigocunhaa commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/WorkflowMetricsAllItemsListTransitionTasks.testcase
> +		MenuItem.click(menuItem = "Approve");
Replace "Approve" with "Reprove"

2021-06-18 15:56 UTC, rodrigocunhaa commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/WorkflowMetricsAllItemsListTransitionTasks.testcase
> +		Alert.viewSuccessMessage();
Here you should assert that the Process Step column is now displaying "Update" for both tasks.

2021-06-18 20:37 UTC, PauloVAS commented
@rodrigocunhaa, done!

2021-06-25 13:20 UTC, rodrigocunhaa commented
Just started reviewing :)

2021-06-25 13:52 UTC, rodrigocunhaa commented
Hi @PauloVAS ,

You still missed one thing. You should assert that the Update status is displayed for both tasks. Since it is a small fixed, I made it here: https://github.com/rodrigocunhaa/liferay-portal/pull/617

Thanks!

2021-06-25 13:52 UTC, closed without merging