LRQA-68830
rodrigocunhaa/liferay-portal pull request #803
Opened 2021-07-22 22:13 UTC by PauloVAS

2021-07-22 22:13 UTC, liferay-continuous-integration commented
Please only forward critical changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing 7.4 DXP EP3 & CE GA3 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-07-22 22:13 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-07-22 22:14 UTC, PauloVAS commented
ci:test:sf

2021-07-22 22:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/483/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-source-format/builds/483/jenkins-report.html">here</a>.</b></p>

2021-07-22 22:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f47c6ac081ab80c4c744698e185d77ade2758188">f47c6ac081ab80c4c744698e185d77ade2758188</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/LRQA-68830">LRQA-68830</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/5faa82eca8c33a4a1c39bcabf216473944bbf2fa">5faa82eca8c33a4a1c39bcabf216473944bbf2fa</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/483/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/483/jenkins-report.html">here</a>.</h5></details></html>

2021-07-22 22:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/483/">test-portal-source-format#483</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/483/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/803">rodrigocunhaa#803</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1548938402">[master] ci:test:sf - PauloVAS &gt; rodrigocunhaa - PR#803 - 2021-07-22[15:14:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/758/">publish-testray-report#758</a><br/></div></div>

2021-08-12 17:25 UTC, lucasperj requested changes

2021-08-12 17:25 UTC, lucasperj commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/MyWorkflowTasks.testcase
> +			locator1 = "//div[contains(@class,'sheet-text text-center')]",
You can use [ locator1 = "Message#EMPTY_INFO" ].

2021-08-12 19:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/3284/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com//userContent/jobs/test-portal-source-format/builds/3284/jenkins-report.html">here</a>.</b></p>

2021-08-12 19:08 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/3284/">test-portal-source-format#3284</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/3284/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/803">rodrigocunhaa#803</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1552978192">[master] ci:test:sf - PauloVAS &gt; rodrigocunhaa - PR#803 - 2021-08-12[12:04:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9938/">publish-testray-report#9938</a><br/></div></div>

2021-08-13 19:11 UTC, lucasperj approved these changes

2021-08-19 16:39 UTC, lucasperj requested changes

2021-08-19 16:39 UTC, lucasperj commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/macros/Workflow.macro
> +	}
Change the macro name to catch both areas (AssignedToMe/AssignedToMyRoles)

2021-08-19 16:39 UTC, lucasperj commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/paths/MyWorkflowTasks.path
> +</tr>
You can make the name of those paths more clear, you can use that same path to both areas (Assigned to me / Assigned to my roles)
Suggestion:

MY_WORKFLOW_TASKS_SEARCH_INPUT_FIELD
MY_WORKFLOW_TASKS_SEARCH_ICON
Remember to change the names at the created macro (searchAssignedToMe)

2021-08-19 22:05 UTC, PauloVAS commented
@lucasperj , fixed!

2021-08-19 22:05 UTC, PauloVAS commented
ci:test:sf

2021-08-19 22:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/343/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com//userContent/jobs/test-portal-source-format/builds/343/jenkins-report.html">here</a>.</b></p>

2021-08-19 22:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/29659ca5c93fa3a85e562f417451fc62cd9ab55e">29659ca5c93fa3a85e562f417451fc62cd9ab55e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/LRQA-68830">LRQA-68830</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/9f5293a9191c73c4a8a38b1ebd641ba2f7e2ad49">9f5293a9191c73c4a8a38b1ebd641ba2f7e2ad49</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/343/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/343/jenkins-report.html">here</a>.</h5></details></html>

2021-08-19 22:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/343/">test-portal-source-format#343</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/343/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/803">rodrigocunhaa#803</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1554575139">[master] ci:test:sf - PauloVAS &gt; rodrigocunhaa - PR#803 - 2021-08-19[15:05:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/1075/">publish-testray-report#1075</a><br/></div></div>

2021-08-19 22:15 UTC, lucasperj approved these changes

2021-08-23 15:36 UTC, lucasperj commented
Just started reviewing :)

2021-08-30 19:48 UTC, lucasperj commented
Combined and sent on [PR#3](https://github.com/lucasperj/liferay-portal/pull/3). Thank you!

2021-08-30 19:48 UTC, closed without merging