LRQA-68849
rodrigocunhaa/liferay-portal pull request #818
Opened 2021-07-26 20:25 UTC by evanilson-santana

2021-07-26 20:26 UTC, liferay-continuous-integration commented
Please only forward critical changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing 7.4 DXP EP3 & CE GA3 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-07-26 20:26 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-07-26 20:26 UTC, evanilson-santana commented
ci:test:sf

2021-07-26 20:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/547/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-source-format/builds/547/jenkins-report.html">here</a>.</b></p>

2021-07-26 20:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6622dc1d1d269468437da9efc126bac5be5bdec2">6622dc1d1d269468437da9efc126bac5be5bdec2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LRQA-68849">LRQA-68849</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/7948c15113fc6fcb227d7dcdc42cc1699817ed52">7948c15113fc6fcb227d7dcdc42cc1699817ed52</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/547/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/547/jenkins-report.html">here</a>.</h5></details></html>

2021-07-26 20:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/547/">test-portal-source-format#547</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/547/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/818">rodrigocunhaa#818</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1549563458">[master] ci:test:sf - evanilson-santana &gt; rodrigocunhaa - PR#818 - 2021-07-26[13:26:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/1019/">publish-testray-report#1019</a><br/></div></div>

2021-07-29 18:56 UTC, evanilson-santana commented
ci:test:sf

2021-07-29 18:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/634/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com//userContent/jobs/test-portal-source-format/builds/634/jenkins-report.html">here</a>.</b></p>

2021-07-29 18:59 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LRQA-68849">LRQA-68849</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/2b5bb028189e53d9bf0ca6b5ee2a8896c7af44e0">2b5bb028189e53d9bf0ca6b5ee2a8896c7af44e0</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/634/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/634/jenkins-report.html">here</a>.</h5></details></html>

2021-07-29 19:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/634/">test-portal-source-format#634</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/634/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/818">rodrigocunhaa#818</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1550442142">[master] ci:test:sf - evanilson-santana &gt; rodrigocunhaa - PR#818 - 2021-07-29[11:57:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/1263/">publish-testray-report#1263</a><br/></div></div>

2021-08-19 18:43 UTC, lucasperj requested changes

2021-08-19 18:43 UTC, lucasperj commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/MyWorkflowTasks.testcase
> +			value1 = "Within 8 Months");
Try to create macros from these functions when you feel the need to use them in .testcase files. Complementing the comment above, ideal is to use a macro to ensure the position of items, you can replace this piece and use the same macro viewMyWorkflowTaskItemPosition and path MY_WORKFLOW_TASK_ITEM_POSITION that you have created at PR #843. Thank you!

2021-08-19 18:43 UTC, lucasperj commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/MyWorkflowTasks.testcase
> +			value1 = "Within 8 Months");
You can take your own [PR](https://github.com/rodrigocunhaa/liferay-portal/pull/837) as example to what you can do with that one.

2021-08-19 18:43 UTC, lucasperj commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/MyWorkflowTasks.testcase
> +			entryTitle = "Blogs Entry");
You can add another one to check the position.

2021-08-19 18:43 UTC, lucasperj commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/MyWorkflowTasks.testcase
> +			workflowTask = "Review");
In this piece, you can create and them update the due date of Blogs Entry 2 to a date closer, and Blogs Entry 1 to a later date, then, assign both to you and activate the Due Date filter, use a macro to ensure the expected position.

2021-08-19 19:26 UTC, lucasperj approved these changes

2021-08-23 15:37 UTC, lucasperj commented
Just started reviewing :)

2021-08-30 19:55 UTC, lucasperj commented
Combined and sent on [PR#3](https://github.com/lucasperj/liferay-portal/pull/3). Thank you!

2021-08-30 19:55 UTC, closed without merging