LRQA-68843
rodrigocunhaa/liferay-portal pull request #824
Opened 2021-07-27 17:43 UTC by evanilson-santana

2021-07-27 17:43 UTC, liferay-continuous-integration commented
Please only forward critical changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing 7.4 DXP EP3 & CE GA3 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-07-27 17:44 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-07-27 17:44 UTC, evanilson-santana commented
ci:test:sf

2021-07-27 17:45 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/186/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-source-format/builds/186/jenkins-report.html">here</a>.</b></p>

2021-07-27 17:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c6e80ea53d10f06b49d569a7e3866210f39cbad5">c6e80ea53d10f06b49d569a7e3866210f39cbad5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LRQA-68843">LRQA-68843</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/356d8d22a9785f99c2dd3aed08ed423b7b79a6c1">356d8d22a9785f99c2dd3aed08ed423b7b79a6c1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/186/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/186/jenkins-report.html">here</a>.</h5></details></html>

2021-07-27 17:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/186/">test-portal-source-format#186</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/186/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/824">rodrigocunhaa#824</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1549847728">[master] ci:test:sf - evanilson-santana &gt; rodrigocunhaa - PR#824 - 2021-07-27[10:44:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/604/">publish-testray-report#604</a><br/></div></div>

2021-07-27 18:37 UTC, evanilson-santana commented
ci:test:sf

2021-07-27 18:38 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/189/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-source-format/builds/189/jenkins-report.html">here</a>.</b></p>

2021-07-27 18:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1c3571456fc3029793773c7065e8bd9db1a8fd30">1c3571456fc3029793773c7065e8bd9db1a8fd30</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LRQA-68843">LRQA-68843</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/fe120cd1d4e27a160bd4775bf2fa3a63d5fd25af">fe120cd1d4e27a160bd4775bf2fa3a63d5fd25af</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/189/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/189/jenkins-report.html">here</a>.</h5></details></html>

2021-07-27 18:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/189/">test-portal-source-format#189</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/189/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/824">rodrigocunhaa#824</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1549856991">[master] ci:test:sf - evanilson-santana &gt; rodrigocunhaa - PR#824 - 2021-07-27[11:37:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/616/">publish-testray-report#616</a><br/></div></div>

2021-08-19 17:14 UTC, lucasperj requested changes

2021-08-19 17:14 UTC, lucasperj commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/MyWorkflowTasks.testcase
> +		Alert.viewSuccessMessageText(successMessage = "Your request completed successfully.");
The step 7 can be extended, with this you are checking the success message, but it's not making a assert if at the new user, there is a blog assigned to him. You can logout and log in to check if the blogs is present there.

2021-08-19 20:48 UTC, lucasperj approved these changes

2021-08-23 15:59 UTC, lucasperj commented
Just started reviewing :)

2021-08-30 19:47 UTC, lucasperj commented
Combined and sent on [PR#3](https://github.com/lucasperj/liferay-portal/pull/3). Thank you!

2021-08-30 19:47 UTC, closed without merging