LRQA-68834
rodrigocunhaa/liferay-portal pull request #827
Opened 2021-07-27 18:29 UTC by evanilson-santana

2021-07-27 18:29 UTC, liferay-continuous-integration commented
Please only forward critical changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing 7.4 DXP EP3 & CE GA3 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-07-27 18:29 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-07-27 18:30 UTC, evanilson-santana commented
ci:test:sf

2021-07-27 18:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/188/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-source-format/builds/188/jenkins-report.html">here</a>.</b></p>

2021-07-27 18:32 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1c3571456fc3029793773c7065e8bd9db1a8fd30">1c3571456fc3029793773c7065e8bd9db1a8fd30</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LRQA-68834">LRQA-68834</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/099677ce4723a0c3b8efefa6ccf686e11bf506b1">099677ce4723a0c3b8efefa6ccf686e11bf506b1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/188/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/188/jenkins-report.html">here</a>.</h5></details></html>

2021-07-27 18:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/188/">test-portal-source-format#188</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/188/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/827">rodrigocunhaa#827</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1549855350">[master] ci:test:sf - evanilson-santana &gt; rodrigocunhaa - PR#827 - 2021-07-27[11:30:15]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/614/">publish-testray-report#614</a><br/></div></div>

2021-08-19 18:26 UTC, lucasperj requested changes

2021-08-19 18:26 UTC, lucasperj commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/paths/MyWorkflowTasks.path
> +</tr>
You can sync those paths created with other created by Paulo Alves at that [PR](https://github.com/rodrigocunhaa/liferay-portal/pull/823/files). 
 
Suggestion:

MY_WORKFLOW_TASKS_SEARCH_INPUT_FIELD
MY_WORKFLOW_TASKS_SEARCH_ICON
MY_WORKFLOW_TASKS_SEARCH_RESULT_BAR

2021-08-19 18:26 UTC, lucasperj commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/MyWorkflowTasks.testcase
> +		Click(locator1 = "MyWorkflowTasks#MY_WORKFLOW_TASKS_SEARCH_BUTTON");
You can take that piece and create a macro to make search at MyWorkflowTask area, see a example at [PR](https://github.com/rodrigocunhaa/liferay-portal/pull/823/files).

2021-08-19 20:47 UTC, lucasperj approved these changes

2021-08-23 15:39 UTC, lucasperj commented
Just started reviewing :)

2021-08-30 19:54 UTC, lucasperj commented
Combined and sent on [PR#3](https://github.com/lucasperj/liferay-portal/pull/3). Thank you!

2021-08-30 19:54 UTC, closed without merging