LRQA-68840
rodrigocunhaa/liferay-portal pull request #837
Opened 2021-07-29 18:10 UTC by evanilson-santana

2021-07-29 18:10 UTC, liferay-continuous-integration commented
Please only forward critical changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing 7.4 DXP EP3 & CE GA3 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-07-29 18:10 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-07-29 18:10 UTC, evanilson-santana commented
ci:test:sf

2021-07-29 18:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/3186/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com//userContent/jobs/test-portal-source-format/builds/3186/jenkins-report.html">here</a>.</b></p>

2021-07-29 18:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/031d999993110005514c95a85ec9e279e0ae28d5">031d999993110005514c95a85ec9e279e0ae28d5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LRQA-68840">LRQA-68840</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/cebad9428bdd8788f5e530f0188f2a39f31c4ef9">cebad9428bdd8788f5e530f0188f2a39f31c4ef9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3186/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3186/jenkins-report.html">here</a>.</h5></details></html>

2021-07-29 18:17 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3186/">test-portal-source-format#3186</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3186/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/837">rodrigocunhaa#837</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1550434372">[master] ci:test:sf - evanilson-santana &gt; rodrigocunhaa - PR#837 - 2021-07-29[11:12:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/1565/">publish-testray-report#1565</a><br/></div></div>

2021-08-18 01:03 UTC, lucasperj requested changes

2021-08-18 01:03 UTC, lucasperj commented on modules/apps/portal-workflow/portal-workflow-test/src/testFunctional/tests/MyWorkflowTasks.testcase
> +			value1 = "Within 8 Months");
Try to create macros from these functions when you feel the need to use them in `.testcase `files. Complementing the  comment above, ideal is to use a macro to ensure the position of items, you can replace this piece and use the same _macro_ `viewMyWorkflowTaskItemPosition` and _path_ `MY_WORKFLOW_TASK_ITEM_POSITION` that you have created at PR #843. Thank you!

2021-08-18 19:02 UTC, lucasperj approved these changes

2021-08-18 19:06 UTC, lucasperj approved these changes
Very good! Thanks

2021-08-18 21:23 UTC, lucasperj commented
ci:test:sf

2021-08-18 21:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/544/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com//userContent/jobs/test-portal-source-format/builds/544/jenkins-report.html">here</a>.</b></p>

2021-08-18 21:26 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a4e6ca098566e12cd033072c7e5326a3bbe5ae8b">a4e6ca098566e12cd033072c7e5326a3bbe5ae8b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/evanilson-santana/liferay-portal/tree/LRQA-68840">LRQA-68840</a><br/>Branch GIT ID: <a href="https://github.com/evanilson-santana/liferay-portal/commit/765ba17a05d197cb6b967ab341d2c12995f8f5bb">765ba17a05d197cb6b967ab341d2c12995f8f5bb</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/544/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/544/jenkins-report.html">here</a>.</h5></details></html>

2021-08-18 21:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/544/">test-portal-source-format#544</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/544/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/837">rodrigocunhaa#837</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1554235980">[master] ci:test:sf - evanilson-santana &gt; rodrigocunhaa - PR#837 - 2021-08-18[14:23:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/1732/">publish-testray-report#1732</a><br/></div></div>

2021-08-23 15:58 UTC, lucasperj commented
Just started reviewing :)

2021-08-30 19:41 UTC, lucasperj commented
Combined and sent on [PR#3](https://github.com/lucasperj/liferay-portal/pull/3)

2021-08-30 19:41 UTC, closed without merging