Objects Automated Test - LPS-138822 | master
rodrigocunhaa/liferay-portal pull request #981
Opened 2021-09-10 18:59 UTC by PauloVAS

2021-09-10 18:59 UTC, liferay-continuous-integration commented
Please only forward necessary changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing DXP 7.4 GA1 and Portal 7.4 GA4 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-09-10 18:59 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-09-10 18:59 UTC, PauloVAS commented
ci:test:sf

2021-09-10 19:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/336/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com//userContent/jobs/test-portal-source-format/builds/336/jenkins-report.html">here</a>.</b></p>

2021-09-10 19:02 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c406508139ee68d8938a2076c9afa7e56bb47b38">c406508139ee68d8938a2076c9afa7e56bb47b38</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/LPS-138822">LPS-138822</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/426d79dfa7c61384516164a30738f661595b3096">426d79dfa7c61384516164a30738f661595b3096</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/336/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/336/jenkins-report.html">here</a>.</h5></details></html>

2021-09-10 19:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/336/">test-portal-source-format#336</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/336/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/981">rodrigocunhaa#981</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1560342688">[master] ci:test:sf - PauloVAS &gt; rodrigocunhaa - PR#981 - 2021-09-10[12:00:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/1104/">publish-testray-report#1104</a><br/></div></div>

2021-09-10 20:25 UTC, rodrigocunhaa requested changes
Hi @PauloVAS ,

Could you please make the changes that I requested?

Let me know if you have any question.

Thanks!

2021-09-10 20:25 UTC, rodrigocunhaa commented on modules/apps/object/object-test/src/testFunctional/tests/tests/CreateObject.testcase
> +			objectName = "CustomObject");
Since for this test we need to validate that it is possible to create the field, you need to add the field via UI instead of the API.

2021-09-10 20:25 UTC, rodrigocunhaa commented on modules/apps/object/object-test/src/testFunctional/tests/macros/ObjectAdmin.macro
> +	macro viewObjectField {
Change this macro name to `assertObjectField`

2021-09-13 17:47 UTC, PauloVAS commented
@rodrigocunhaa, fixed!

2021-09-13 17:48 UTC, PauloVAS commented
ci:test:sf

2021-09-13 17:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-23.liferay.com/job/test-portal-source-format/6057/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-23.liferay.com//userContent/jobs/test-portal-source-format/builds/6057/jenkins-report.html">here</a>.</b></p>

2021-09-13 17:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/085840d3115742ca246067fb022ccf3aa25fa641">085840d3115742ca246067fb022ccf3aa25fa641</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PauloVAS/liferay-portal/tree/LPS-138822">LPS-138822</a><br/>Branch GIT ID: <a href="https://github.com/PauloVAS/liferay-portal/commit/5fedf7d6749183990ab68081ec9aba081a4fd37c">5fedf7d6749183990ab68081ec9aba081a4fd37c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-source-format/6057/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-source-format/builds/6057/jenkins-report.html">here</a>.</h5></details></html>

2021-09-13 17:56 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-23.liferay.com/job/test-portal-source-format/6057/">test-portal-source-format#6057</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-source-format/builds/6057/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/rodrigocunhaa/liferay-portal/pull/981">rodrigocunhaa#981</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1560848568">[master] ci:test:sf - PauloVAS &gt; rodrigocunhaa - PR#981 - 2021-09-13[10:48:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-23.liferay.com/job/publish-testray-report/1147/">publish-testray-report#1147</a><br/></div></div>

2021-09-13 18:22 UTC, rodrigocunhaa commented
ci:forward

2021-09-13 18:23 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-09-13 18:23 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-09-13 18:23 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-28.liferay.com/job/forward-pullrequest/39//consoleFull)

2021-09-13 18:24 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/107070
[Console](https://test-1-28.liferay.com/job/forward-pullrequest/39//consoleFull)

2021-09-13 18:24 UTC, closed without merging